### PR TITLE
Bump mermaid from 9.2.0 to 9.4.0

### LINKED ISSUE #42: Fontawesome icons not there when generating image
**Describe the bug**
If you try to use a fontawesome icon like fa:fa-phone, it's displayed in the preview but disappear from generated image.

**To Reproduce**
1) Create a test.mmd in vscode.

```
graph LR
test[fa:fa-phone <- Phone]
```

2) See that preview display the phone icon
3) Generate image and see that phone icon is missing.

**Expected behavior**
Fontawesome icons should be generated as well.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Win 10 20 H2
 - VSCode version 1.55.2
 - Extension version 0.11

### LINKED ISSUE #69: Mindmap graphs not working
**Describe the bug**
Using Mindmaps does not appear to be working.
Copying and pasting the example from https://mermaid-js.github.io/mermaid/#/mindmap gives
```
[DigagramParseError]
undefined
```
in the output pane, and no graph is generated, instead a Mermaid error message "Syntax error in graph" is shown in the preview pane.

This same graph works properly at the Mermaid Live editor at https://mermaid.live/

**To Reproduce**
1. Open a new .mmd file
2. Paste in the example text from https://mermaid-js.github.io/mermaid/#/mindmap
3. Save file

**Expected behavior**
Graph is displayed properly as at https://mermaid.live/

**Screenshots**
image

**Desktop:**
 - OS: Ubuntu 20.04.5
 - VSCode 1.73.0
 - Extension tomoyukim.vscode-mermaid-editor@0.17.1

### LINKED ISSUE #72: Sequence Diagram new syntaxes not working
**Describe the bug**
Referencing #69 as template for the same concerns, but for a different type of diagram.

Using a new Sequence Diagram syntax that was introduced in `mermaid` [v9.4.0](https://github.com/mermaid-js/mermaid/releases/tag/v9.4.0) will break the preview.
Copying and pasting the example from https://mermaid.js.org/syntax/sequenceDiagram.html#grouping-box gives
```
[DigagramParseError]
undefined
```

I use this extension at work. Would be great to benefit by shipping the extension with a newer version of the library that supports the syntax.

**To Reproduce**
* Open a new .mmd file
* Paste in the example text from https://mermaid.js.org/syntax/sequenceDiagram.html#grouping-box
* Save file
* See error

**Expected behavior**
Graph is displayed properly as at https://mermaid.js.org/syntax/sequenceDiagram.html#grouping-box.

**Note:** Showing expected behavior https://mermaid.live/ is currently not possible. It's still running on v9.3.0 of the library.

**Screenshots**

**Desktop (please complete the following information):**
Doesn't really matter which OS and VSCode version. I have an older PC running macOS Mojave 10.14.6 and VS
 - OS: macOS Ventura 13.2.1 (same issue with older PC on macOS Mojave 10.14.6)
 - VSCode version: 1.75.1 (same issue with older PC on 1.74.2)
 - Extension version: tomoyukim.vscode-mermaid-editor@0.17.1

### PR DESCRIPTION
**Pull request by KajiTetsushi**
Fixes #42
Fixes #69
Fixes #72

Supports the latest syntaxes without venturing into `mermaid` v10.

The only breaking change from `mermaid` [v9.4.0](https://github.com/mermaid-js/mermaid/releases/tag/v9.4.0) that I can tell is the async rendering method of mind map and timeline diagrams. Since [main.js](https://github.com/tomoyukim/vscode-mermaid-editor/blob/v0.17.1/media/main.js) doesn't use `mermaid.render()` which could lead to potential migration issues, I assume there's no problem here. Let me know if there's a blind spot.

> - Mind map and timeline diagrams are lazy loaded by mermaid. In order to use these diagrams you need to use the renderAsync method of rendering. The @mermaid-js/mermaid-mindmap package is deprecated by this.

-----
#### Mind maps
image

#### Timelines
image

#### Boxes in sequence diagrams
image

#### Font Awesome in graphs (and any other diagram that supports it)
image

### CODE REVIEW

**Comment by KajiTetsushi** [comment]
False negative on `Job mac`: https://dev.azure.com/tomoyukim-vscode-extension/vscode-mermaid-editor-pipeline/_build/results?buildId=131&view=logs&j=291b3e6c-60a9-5f30-6b17-b27c7388dcd0&t=73e02479-b06a-558b-66de-a6177ecb9da0. Looks like a network error.

It reads...
```
$ node ./out/test/runTest
Downloading VS Code 1.75.1 from https://update.code.visualstudio.com/1.75.1/darwin/stable
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (node:_http_client:494:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read'
}
```

Not familiar with Azure Pipelines. Any further action I can take here?

**Comment by tomoyukim** [comment]
Thank you for your PR. It seems like an error from node.js. I guess it comes from the infrastructure in Azure Pipeline. Could you try to update the [node version](https://github.com/tomoyukim/vscode-mermaid-editor/blob/master/azure-pipeline.yaml#L24) in the pipeline file to 17.x?

**Comment by tomoyukim** [comment]
Or I'll fix it on my side after emerging this PR anyway. Thank you again!

**Comment by KajiTetsushi** [comment]
> It seems like an error from node.js. I guess it comes from the infrastructure in Azure Pipeline. Could you try to update the [node version](https://github.com/tomoyukim/vscode-mermaid-editor/blob/master/azure-pipeline.yaml#L24) in the pipeline file to 17.x?

@tomoyukim I'm a bit cautious about odd numbers in the node major versions, because they're always advertised to be experimental and have very short support lifespan compared to even numbers. In [the maintenance schedule](https://nodejs.dev/en/about/releases/), it's not even on the list. [Here's even more evidence.](https://www.makeuseof.com/nodejs-17-reached-eol-what-does-that-mean-for-you/)

I'd go for 18.x. It's the new replacement for 16, it seems.

If I change it, will Azure Pipeline pick up on it and let this PR pass?

**Comment by KajiTetsushi** [comment]
@tomoyukim 🟢 all green

**Pull request merged**
